V4.0 Lasrge Tx Support
ayende/ravendb pull request #4408
Opened 2016-09-15 13:05 UTC by aviviadi

http://issues.hibernatingrhinos.com/issue/RavenDB-4806

2016-09-16 08:34 UTC, ayende commented on src/Raven.Server/Config/Categories/StorageConfiguration.cs
> +        public bool SupportLargeTransactions { get; set; }
Should remove this, we are always supporting large transactions

2016-09-16 08:35 UTC, ayende commented on src/Sparrow/Compression/LZ4.cs
> +            if (inputLength < int.MaxValue && outputLength < int.MaxValue)
There is an error here, LZ4 can't actually handle 2GB size, it is something a bit less than that, and you need to take that into account.

2016-09-16 08:36 UTC, ayende commented on src/Sparrow/Compression/LZ4.cs
> +                totalOutputSize += Encode64(input, output, partInputLength, partOutputLength, acceleration);
In here, you are always compressing the first part of the data, and never the latter part.
The `input` and `output` values aren't change, and that is what it is using.

2016-09-16 08:36 UTC, ayende commented on src/Sparrow/Compression/LZ4.cs
> +            if (inputLength < int.MaxValue && outputLength < int.MaxValue)
At any rate, we are probably better at compressing at 1GB size, to ensure that we are away from the limit.

2016-09-16 08:37 UTC, ayende commented on src/Sparrow/Compression/LZ4.cs
> +            if (inputLength < int.MaxValue && outputLength < int.MaxValue)
Same size issue here.

2016-09-16 08:37 UTC, ayende commented on src/Sparrow/Compression/LZ4.cs
> +                totalOutputSize += Decode64(input, partInputLength, output, partOutputLength, false);
Same decoding issue here, you are not moving the input & output here.

2016-09-16 08:39 UTC, ayende commented on src/Voron/Impl/Backup/IncrementalBackup.cs
> +                        using (var options = StorageEnvironmentOptions.ForPath(Path.Combine(outPath, dir.Key), false)) // TODO : should we support here large tx ?
Yes

2016-09-16 08:39 UTC, ayende commented on src/Voron/Impl/Journal/JournalFile.cs
> +                Debug.Assert(pages.NumberOfPages < int.MaxValue);
This is not enough here, we need to actually handle this scenario

2016-09-16 08:39 UTC, ayende commented on src/Voron/Impl/Journal/JournalFile.cs
> +                Debug.Assert(pages.NumberOfPages < int.MaxValue);
And in general, if the transaction size is bigger than 2GB, it isn't lazy.
Also, you are comparing the number of pages to 2GB, but that isn't the actual size.

2016-09-16 08:40 UTC, ayende commented on src/Voron/Impl/Journal/JournalReader.cs
> +                throw new InvalidDataException(
Move the throw to a dedicated method.

2016-09-16 08:40 UTC, ayende commented on src/Voron/Impl/Journal/JournalReader.cs
> +            int numOfPages = unchecked((int)result);
You don't need the unchecked here.

2016-09-16 08:42 UTC, ayende commented on src/Voron/Impl/Journal/LazyTransactionBuffer.cs
> +            Debug.Assert(pages.NumberOfPages < int.MaxValue);
Wrong calculation here, and assert doesn't cut it.

2016-09-16 08:47 UTC, ayende commented on src/Voron/Impl/Journal/WriteAheadJournal.cs
> +                CurrentFile = NextFile((int)pages.NumberOfPages);
There seems to be a repeating pattern of mixing the number of pages and the actual size.
int.MaxValue * 4KB = 16TB.

2016-09-16 08:48 UTC, ayende commented on src/Voron/Impl/Journal/WriteAheadJournal.cs
> +                outputBufferSize = maxSizeRequiringCompression + (maxSizeRequiringCompression / 255) + 16;
Explain the math here, please.

2016-09-16 08:48 UTC, ayende commented on src/Voron/Impl/Paging/AbstractPagerExtensions.cs
> +            if (result > int.MaxValue)
Same pages vs size error.

2016-09-16 08:49 UTC, ayende commented on src/Voron/Impl/Scratch/ScratchBufferPool.cs
> +                else if (_options.SupportLargeTransactions)
This should be the default, but we need to have a discussion on this to make sure we have a coherent strategy here.

2016-09-16 08:49 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +        public bool SupportLargeTransactions { get; set; }
Remove this, it is the deafult.

2016-09-16 08:50 UTC, ayende commented on test/SlowTests/Voron/HugeTransactions.cs
> +        public unsafe void CanWriteBigTransactions(long transactionSizeInGb)
Those are actually running concurrently, and it is really killing the test machine.
We can just have 2 & 6 GB tests, and make sure that they aren't running concurrently.

2016-09-16 08:50 UTC, ayende requested changes

2016-09-20 16:57 UTC, aviviadi commented on src/Voron/Platform/Win32/Win32JournalWriter.cs
> +                WriteFile(position, p, _maxNumberOfPagesPerSingleWrite);
TODO : We need to make a single call or mark the entire section until we finish all the segments writes

2016-09-20 16:59 UTC, aviviadi commented on src/Voron/Impl/Journal/WriteAheadJournal.cs
> +            var fullTxBuffer = outputBuffer + (pageCountIncludingAllOverflowPages*(long)pageSize);
This "little" cast was the buggy issue for large writes

2016-09-21 07:42 UTC, merged