RavenDB-6602 implementation
ayende/ravendb pull request #4628
Opened 2017-03-30 16:11 UTC by myarichuk

there is still ReplicationWithFailover::LoadDocumentsWithFailOver() test to fix -> related to this issue

2017-04-02 21:30 UTC, ayende requested changes

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Documents/DocumentStore.cs
> +            var lazy = _requestExecuters.AddOrUpdate(databaseName,
Why is this called for? Doesn't seem to be doing anything

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Documents/DocumentStore.cs
> +                {
Doesn't the existing value need to be disposed?

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Http/ReadBehavior.cs
> +        ConversationNodeOnly,
What is `Conversation` ? That is not a term I'm familiar with.

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +            //_updateFailingNodesStatus = new Timer(UpdateFailingNodesStatusCallback, null, TimeSpan.FromMinutes(1),
This is not part of the client. The client merely update its topology every minutes, nothing more.

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +            var lockTaken = _updateTopologySemaphore.Wait(0);
What is actually being protected in this lock?

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Documents/DocumentStoreBase.cs
> +        internal abstract void RedirectRequestExecuterTo(string url, string databaseName = null);
This is never called

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +                            if (command.Result.Nodes.Count > 0 && _nodeSelector.OnUpdateTopology(command.Result, forceUpdate:true))
why are you calling the topology in the middle of error handling?

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +            if (_requiresTopologyUpdates && Interlocked.CompareExchange(ref _hasUpdatedTopologyAtLeastOnce, 1, 0) == 0)
Bad, if we have concurrent calls, the first one will run this, the other will not wait

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +                        if (response.Headers.Contains(Constants.Headers.ForceTopologyUpdate))
Under what conditions will the server send it?

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +                        if (response.Headers.Contains(Constants.Headers.ForceTopologyUpdate))
And why are we forcing the client to wait for the next topology when we already have the response for what it asked for?

2017-04-02 21:30 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +            if (node.ClusterToken != null)
This is not a cluster token, it is the current node _for that specific machine_

2017-04-04 14:31 UTC, myarichuk commented on src/Raven.Client/Http/ReadBehavior.cs
> +        ConversationNodeOnly,
I think I just transcribed it from our discussion about this. I will change this to "CurrentNodeOnly" kind of naming

2017-04-05 09:20 UTC, closed without merging

2017-04-05 10:26 UTC, myarichuk commented on src/Raven.Client/Http/RequestExecutor.cs
> +                        if (response.Headers.Contains(Constants.Headers.ForceTopologyUpdate))
Under what conditions will the server send it? --> we have talked that the server will send it when senator is changed or when there are any changes to topology that come from the server-side